version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/templates/basic-js"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/templates/basic-ts"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/templates/checks-js"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/templates/deploy-js"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/templates/git-data-js"
    schedule:
      interval: "daily"
