#!/bin/bash

set -e

# Ensure we're always running from the project root
cd "$(dirname "$0")/.."

PROJECT_DIR=$(pwd)
TEMP_DIR="$PROJECT_DIR"/tmp
mkdir -p $TEMP_DIR

for i in $PROJECT_DIR/templates/*
do
  template=$(basename $i)
  echo $template
  cd $TEMP_DIR
  rm -rf $template

  $PROJECT_DIR/bin/create-probot-app.js \
    --appName "travis-template-test" \
    --desc "A Probot App for building on Travis" \
    --author "Pro Bawt" \
    --email "probot@example.com" \
    --homepage "https://probot.github.io" \
    --user "probot" \
    --template $template \
    --repo "probot/create-probot-app-$template" \
    $template

  cd $template
  npm test
done
