#!/bin/sh

bin/create-probot-app.js \
  --appName "travis-template-test" \
  --desc "A Probot App for building on Travis" \
  --author "Pro Bawt" \
  --email "probot@example.com" \
  --homepage "https://probot.github.io" \
  --user "probot" \
  --template "basic-js" \
  --repo "probot/create-probot-app-basic-js" \
  travis-template-test

cd travis-template-test
npm test
